model:
  embedding_dim: 1024
  ff_dim: 4096
  transformer_heads: 8
  transformer_blocks: 4
  dimensions:
    x: 256
    y: 240
  feature_channels: [64, 128, 128]
  spatial_channels: 64
  sequence_length: 64

training:
  batch_size: 1
  learning_rate: 0.0001
  weight_decay: 0.0001
  patience: 10
  stride: 1
  data_dir: "idm/data/numpy"
  test_train_split: 0.9
  min_class_weight: 1000
  epochs: 100